### ISSUE TITLE
Preparations round 2

### ISSUE THREAD

**Issue by ivarconr** [ivarconr/ws-node-intro#3]
- [X] Booke rom 15. desember (lekestue + snøfreser) @ivarconr
- [x] Sende invitasjon til alle deltaker fra ventelisten @ivarconr
- [x] Fikse litt på npm presentasjon + codealong istedenfor oppgavesett @trygve-lie
- [x] Kort presentasjon av hva som følger med Node (APIer, hva er "bare" JS,  etc) @trygve-lie
- [ ] Forbedre oppgavebeskrivelser (mer eksempler, tydeligere mål etc) @sveisvei @ivarconr
- [ ] Legge inn noen npm oppgaver i express-oppgavene @lagben 
- [ ] Follow presentasjon til slutt => hvordan lære mer, bra ressurser, bøker osv. @sveisvei @ivarconr @trygve-lie @lagben

**Comment by trygve-lie** [comment]
The NPM part is quite OK for me to run out of the box. I've changed a couple of small things and added a couple of things. I added something about what defines a package (that an directory with just an index.js are pr def an package) and I want to say something about NODE_ENV which affect installation of devDependencies.

**Comment by trygve-lie** [comment]
Some resources for js and node.js (I think we need to list a bit of both):

JS:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/A_re-introduction_to_JavaScript (worth pointing out as a must read on MDN)
- http://exploringjs.com/

Node.js:
- https://nodejs.org/dist/latest-v7.x/docs/api/
- https://blog.risingstack.com/node-hero-tutorial-getting-started-with-node-js/
- http://www.nodebeginner.org/
- https://github.com/substack/stream-handbook

Worth mentioning as a resource:
- http://node.green/

**Comment by trygve-lie** [comment]
I've added a presentation on misc stuff around API's where I'm trying to point out what are plain JS, what are APIs found in browsers and what are Node.js API's. I am also trying to point out what API's does the browser and node.js share and not share and which API's do exist in both the browser and Node.js but are totally different. 

I'm also saying a little bit about XHR / fetch in the browser which we use the http module for in node where I just want to point out that fetch are a browser API which would be natural to have in Node.js but that we do not have and that there are user land modules for such.

I'm also doing a small round of info on module systems.
